project:
  type: website

website:
  title: "IRN LiStat"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: actus.qmd
        text: Actualités
      - href: actions.qmd
        text: Actions & Thèmes
      - href: bureau.qmd
        text: Bureau  
      - href: contact.qmd
        text: Contact & Liste de diffusion

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
