---
title: "Actualités"
---

## Webinaire : retour sur les mobilités 2024 (à venir)

## Soutien financier 2025

Pour cette année 2025, le bureau envisage de reconduire des appels à manifestation d’intérêt autour des actions suivantes :

* Organisation d’école chercheur ou de workshop avec une ambition de rayonnement sous-régionale

* Mobilité individuelle que ce soit
  + Pour un échange bilatéral
  + Pour participer à des colloques scientifiques en rapport avec les thèmes centraux de LiStat (e.g. [journées du GdR Ecostat](https://ecostat2025.sciencesconf.org/) les 28-29 avril prochain à Metz, JDS’25 à Marseille début juin, etc ; ces deux exemples métropolitains ne sont pas exclusifs bien sûr de colloques internationaux) et en profiter pour travailler avec des collègues sur place (dans un souci de sobriété, nous souhaitons éviter les voyages courts dont le seul objectif est de participer à un colloque).\

Pour nous faire remonter vos demandes, merci d’utiliser [le formulaire suivant](https://docs.google.com/forms/d/1pNEigBTcj7ak2umnSSfu_Xvf7fxVLrguZJFeXxCrPXw/edit). Nous vous invitons à nous faire part de vos demandes **avant le 28 mars 2025**. Le formulaires restera ouvert après le 28 mars mais le budget disponible dépendra des premiers arbitrages. Les personnes bénéficiaires d’un soutien LiStat en 2024 ne seront pas prioritaires (mais elles demeurent éligibles bien sûr). 

## Financement de mobilités

L'IRN LiStat propose de soutenir financièrement des **mobilités inter-laboratoires** pour autant qu'un des laboratoires est **un laboratoire du sud** et que le travail envisagé est cohérent avec les ambitions scientifiques de LiStat, à savoir le développement :

-   De méthodes statistiques motivées par les enjeux mondiaux concernant la biodiversité, la santé et les écosystèmes exploités,

-   De partages de compétences et expériences incluant des partenaires du sud,

-   D'une science ouverte comme pratique standard.

## Budget et conditions

Un budget indicatif de 1 000 € par mobilité est envisagé pour aider à la prise en charge du transport et/ou du logement pendant la mobilité.\
Cela peut aider à prolonger une mission déjà prévue, ou encore à participer à un évènement scientifique (formation, workshop, école d'été, etc) en complétant le déplacement par une collaboration avec des scientifiques sur place.

Les **conditions d'éligibilité** sont donc :

-   Au moins l'un des laboratoires concernés (accueil et/ou provenance) est un **laboratoire au sud**

-   La personne concernée par la mobilité peut être en doctorat, ou un.e scientifique junior ou senior

-   Le sujet doit être cohérent avec les ambitions scientifiques de LiStat

-   La mobilité doit être **réalisée avant fin 2025**

## Comment postuler ?

Dans ce cadre que nous souhaitons très souple, merci de nous faire remonter vos demandes d'ici via le [formulaire suivant]( https://docs.google.com/forms/d/1pNEigBTcj7ak2umnSSfu_Xvf7fxVLrguZJFeXxCrPXw/edit).\

Il sera demandé aux personnes ayant bénéficié d'un soutien LiStat d'envoyer quelques lignes de présentation de leur travail. Ce court texte sera ensuite diffusé sur la liste de diffusion LiStat et archivé sur le site web de LiStat.
